<?php

namespace reketaka\nodes\controllers;

use Yii;
use reketaka\nodes\models\NodesControllerCatalog;
use reketaka\nodes\models\NodesControllerCatalogSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use reketaka\nodes\Module;

/**
 * ControllerCatalogController implements the CRUD actions for NodesControllerCatalog model.
 */
class ControllerCatalogController extends Controller
{


    public function beforeAction($action)
    {
        $this->view->title = Module::t('titles', Yii::$app->controller->id.'/'.Yii::$app->controller->action->id);
        \reketaka\nodes\assets\NodeAssets::register($this->view);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionReIndex(){
        NodesControllerCatalog::reIndex();

        return $this->redirect(Yii::$app->request->referrer?Yii::$app->request->referrer:Url::home());
    }

    /**
     * Lists all NodesControllerCatalog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NodesControllerCatalogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single NodesControllerCatalog model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new NodesControllerCatalog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NodesControllerCatalog();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'controllers'=>$controllers
            ]);
        }
    }

    /**
     * Updates an existing NodesControllerCatalog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing NodesControllerCatalog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the NodesControllerCatalog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return NodesControllerCatalog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NodesControllerCatalog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
